#pragma once

#define NODE_HCP_DRAW_BODY_COLOR          ImColor(75, 75, 75, 255);
#define NODE_HCP_DRAW_BODY_HOVERED_COLOR  ImColor(100, 100, 100, 255);
#define NODE_HCP_DRAW_BODY_SELECTED_COLOR ImColor(150, 150, 150, 255);
#define NODE_HCP_DRAW_OUTLINE_COLOR       ImColor(175, 175, 175, 255);

// Voxel context id
//#define NODE_CATEGORY_ID_GENERATOR 10000
#define NODE_TYPE_ID_HCP_VOXEL             10000
#define NODE_TYPE_ID_CART_TO_HCP_VOXEL     10001
#define NODE_TYPE_ID_HCP_VOXEL_AUTOMATA    10100
#define NODE_TYPE_ID_HCP_VOXEL_TRANSLATION 10200
#define NODE_TYPE_ID_HCP_VOXEL_INTERACTION 10500


#define CONTEXT_ID_HCP_VOXEL     1000
#define HCP_CONTEXT_POINT_CLOUD	 1100

#define DATA_VALUE_TYPE_HCP_VOXEL_MATRIX 10500

// Voxel value id
#define HCP_VOXEL_MATRIX_VALUE     0
#define HCP_VOXEL_MATRIX_OPERATOR  1

// Voxel functions
#define HCP_VOXEL_FUNCTION_ENTITY      1


#define HCP_VOXEL_FUNCTION_TRANSLATION 100
#define HCP_VOXEL_FUNCTION_INTERACTION 200
