#pragma once

#define NODE_HEX_DRAW_BODY_COLOR            ImColor(75, 75, 105, 255);
#define NODE_HEX_DRAW_BODY_HOVERED_COLOR    ImColor(100, 100, 130, 255);
#define NODE_HEX_DRAW_BODY_SELECTED_COLOR   ImColor(150, 150, 175, 255);
#define NODE_HEX_DRAW_OUTLINE_COLOR         ImColor(175, 175, 200, 255);

// Voxel context id
//#define NODE_CATEGORY_ID_GENERATOR 10000
#define NODE_TYPE_ID_HEX_SURFACE             11000
#define NODE_TYPE_ID_HEX_SURFACE_AUTOMATA    11100
#define NODE_TYPE_ID_HEX_SURFACE_TRANSLATION 11200
#define NODE_TYPE_ID_HEX_SURFACE_INTERACTION 11500

// Hex surface context id
#define CONTEXT_ID_HEX_SURFACE_GRID        2000
#define CONTEXT_ID_HEX_SURFACE_POINT_CLOUD 2100

#define DATA_VALUE_TYPE_HEX_SURFACE_GRID   11500

// Hex value id
#define HEX_SURFACE_GRID_VALUE     20
#define HEX_SURFACE_GRID_OPERATOR  21

// hex functions
#define HEX_SURFACE_FUNCTION_ENTITY      1

#define HEX_SURFACE_FUNCTION_TRANSLATION 2
#define HEX_SURFACE_FUNCTION_INTERACTION 200
